-- Semantic glyphs used for state, diagnostics, and focused tool UIs.
return {
    terminal = '',
    repl = '',
    cwd = '󰉋',
    toggle_on = '',
    toggle_off = '',
    learning = '󰗚',
    maximize = '󰁌',
    recording = '󰑋',
    format = '󰉼',
    success = '',
    pending = '',
    error = '',
    warn = '',
    info = '',
    hint = '',
    breakpoint = '',
    stopped = '',
    bug = '',
    todo = '',
    hack = '',
    perf = '',
    note = '',
    test = '󰙨',
    fold_open = '',
    fold_closed = '',
}
