local icons = require('config.icons')

assert(icons.terminal and icons.error and icons.learning, 'icon table is incomplete')
assert(vim.fn.exists(':KeymapManual') == 2, 'KeymapManual command is missing')
assert(vim.fn.maparg(']t', 'n') ~= '', 'next TODO mapping is missing')
assert(vim.fn.maparg('<leader>qt', 'n') ~= '', 'TODO list mapping is missing')
assert(vim.fn.maparg('<leader>aa', 'n') ~= '', 'select-all mapping is missing')
assert(vim.fn.maparg('<leader>ay', 'n') ~= '', 'copy-all mapping is missing')
assert(vim.fn.maparg('<leader>ax', 'n') ~= '', 'cut-all mapping is missing')
assert(vim.fn.maparg('<leader>wm', 'n') ~= '', 'maximize mapping is missing')
assert(vim.fn.maparg('<leader>mm', 'n') ~= '', 'minimal mode mapping is missing')
assert(vim.fn.maparg('<leader>mn', 'n') ~= '', 'normal mode mapping is missing')
assert(vim.fn.exists(':ModeMinimal') == 2, 'ModeMinimal command is missing')
assert(vim.fn.exists(':ModeNormal') == 2, 'ModeNormal command is missing')
assert(vim.fn.maparg('<leader>rr', 'n') ~= '', 'REPL restart mapping is missing')
assert(vim.fn.exists(':Maximize') == 2, 'Maximize command is missing')
assert(vim.fn.maparg('s', 'n', false, true).desc == 'Flash jump', 'Flash mapping is missing')
assert(vim.fn.maparg('ys', 'n') ~= '', 'surround add mapping is missing')
assert(vim.fn.maparg('ds', 'n') ~= '', 'surround delete mapping is missing')
assert(vim.fn.maparg('cs', 'n') ~= '', 'surround replace mapping is missing')

dofile(vim.fn.stdpath('config') .. '/tests/toggles.lua')
